'use client';
import { motion } from 'framer-motion';
import { BarChart, PieChart, TrendingUp, Activity, FileText } from 'lucide-react';

export default function ReportsDashboard() {
  return (
    <div className="space-y-8 pb-20">
      <div>
        <h1 className="text-3xl font-heading font-bold text-foreground flex items-center gap-3"><BarChart className="text-primary"/> Analytics & Reports</h1>
        <p className="text-muted mt-2">Monthly shelter impact and performance metrics.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        
        {/* Fake Line Chart */}
        <div className="bg-surface border border-border rounded-3xl p-8 shadow-soft">
          <h2 className="text-lg font-bold text-foreground mb-6 flex items-center gap-2"><TrendingUp size={20} className="text-primary"/> Monthly Adoptions</h2>
          <div className="h-64 flex items-end justify-between gap-2 border-b border-l border-border p-4">
            <div className="w-full bg-primary/20 hover:bg-primary/40 transition-colors rounded-t-lg" style={{ height: '40%' }}></div>
            <div className="w-full bg-primary/30 hover:bg-primary/50 transition-colors rounded-t-lg" style={{ height: '60%' }}></div>
            <div className="w-full bg-primary/40 hover:bg-primary/60 transition-colors rounded-t-lg" style={{ height: '30%' }}></div>
            <div className="w-full bg-primary/60 hover:bg-primary/80 transition-colors rounded-t-lg" style={{ height: '70%' }}></div>
            <div className="w-full bg-primary hover:bg-primary/90 transition-colors rounded-t-lg" style={{ height: '90%' }}></div>
          </div>
          <div className="flex justify-between text-xs text-muted font-bold mt-4 px-4">
            <span>May</span>
            <span>Jun</span>
            <span>Jul</span>
            <span>Aug</span>
            <span>Sep</span>
          </div>
        </div>

        {/* Fake Donut Chart */}
        <div className="bg-surface border border-border rounded-3xl p-8 shadow-soft flex flex-col justify-center items-center">
          <h2 className="text-lg font-bold text-foreground mb-8 flex items-center gap-2 w-full"><PieChart size={20} className="text-warning"/> Intake Demographics</h2>
          
          <div className="relative w-48 h-48 rounded-full border-[1.5rem] border-primary/20 flex items-center justify-center">
            <div className="absolute inset-0 rounded-full border-[1.5rem] border-transparent border-t-primary border-r-primary rotate-45"></div>
            <div className="absolute inset-0 rounded-full border-[1.5rem] border-transparent border-l-warning -rotate-45"></div>
            
            <div className="text-center">
              <span className="block text-2xl font-black text-foreground">128</span>
              <span className="text-xs font-bold text-muted uppercase">Total</span>
            </div>
          </div>
          
          <div className="flex gap-6 mt-8">
            <div className="flex items-center gap-2 text-sm font-bold text-muted"><span className="w-3 h-3 rounded-full bg-primary"></span> Dogs (68%)</div>
            <div className="flex items-center gap-2 text-sm font-bold text-muted"><span className="w-3 h-3 rounded-full bg-warning"></span> Cats (32%)</div>
          </div>
        </div>

      </div>

      <div className="bg-surface border border-border rounded-3xl p-8 shadow-soft">
        <h2 className="text-lg font-bold text-foreground mb-6 flex items-center gap-2"><Activity size={20} className="text-secondary"/> Recent Exports</h2>
        <div className="space-y-4">
          {[1, 2, 3].map((i) => (
            <div key={i} className="flex items-center justify-between p-4 border border-border rounded-2xl hover:bg-black/5 transition-colors cursor-pointer">
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 bg-secondary/10 text-secondary rounded-xl flex items-center justify-center">
                  <FileText size={20} />
                </div>
                <div>
                  <h4 className="font-bold text-foreground">Shelter Population Report - Q{4-i}</h4>
                  <p className="text-xs font-bold text-muted">Generated by Admin • 2 days ago</p>
                </div>
              </div>
              <button className="bg-background border border-border px-4 py-2 text-xs font-bold rounded-lg hover:bg-black/5 transition-colors">Download PDF</button>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
